// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace BimCollab.ClashDetection.Specs.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "US1")]
    public partial class ClashDetectionFeature : object, global::Xunit.IClassFixture<ClashDetectionFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "US1"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Clash Detection", "    As a BIM system consumer\n    I want to detect clashes in building site plans\n" +
                "    So that design conflicts and zoning violations are identified early", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ClashDetection.feature"
#line hidden
        
        public ClashDetectionFeature(ClashDetectionFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 7
    #line hidden
#line 8
        await testRunner.GivenAsync("a site plan with width 1000 and length 500", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/ClashDetection.feature.ndjson", 11);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Example dataset produces correct clashes")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Clash Detection")]
        [global::Xunit.TraitAttribute("Description", "Example dataset produces correct clashes")]
        public async global::System.Threading.Tasks.Task ExampleDatasetProducesCorrectClashes()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Example dataset produces correct clashes", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 10
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Type",
                            "Width",
                            "Length",
                            "X",
                            "Y"});
                table1.AddRow(new string[] {
                            "School A",
                            "School",
                            "100",
                            "100",
                            "0",
                            "0"});
                table1.AddRow(new string[] {
                            "Office B",
                            "Office",
                            "100",
                            "100",
                            "200",
                            "0"});
                table1.AddRow(new string[] {
                            "Nightclub C",
                            "Nightclub",
                            "100",
                            "100",
                            "50",
                            "50"});
                table1.AddRow(new string[] {
                            "Stadium D",
                            "Stadium",
                            "200",
                            "200",
                            "800",
                            "350"});
                table1.AddRow(new string[] {
                            "Residence E",
                            "ResidentialBuilding",
                            "80",
                            "80",
                            "60",
                            "200"});
#line 11
        await testRunner.GivenAsync("the following buildings exist on the site plan:", ((string)(null)), table1, "Given ");
#line hidden
#line 18
        await testRunner.WhenAsync("I run clash detection", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
        await testRunner.ThenAsync("a clash of type \"Overlap\" with severity \"Critical\" should be detected for buildin" +
                        "gs \"School A\" and \"Nightclub C\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 20
        await testRunner.AndAsync("a clash of type \"BoundaryViolation\" with severity \"Critical\" should be detected f" +
                        "or building \"Stadium D\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
        await testRunner.AndAsync("a clash of type \"ZoningViolation\" with severity \"Warning\" should be detected for " +
                        "buildings \"School A\" and \"Nightclub C\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
        await testRunner.AndAsync("a clash of type \"ZoningViolation\" with severity \"Warning\" should be detected for " +
                        "buildings \"Residence E\" and \"Nightclub C\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
        await testRunner.AndAsync("4 clashes should be detected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="No clashes for valid layout")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Clash Detection")]
        [global::Xunit.TraitAttribute("Description", "No clashes for valid layout")]
        public async global::System.Threading.Tasks.Task NoClashesForValidLayout()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("No clashes for valid layout", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 25
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Type",
                            "Width",
                            "Length",
                            "X",
                            "Y"});
                table2.AddRow(new string[] {
                            "Building A",
                            "Office",
                            "100",
                            "100",
                            "0",
                            "0"});
                table2.AddRow(new string[] {
                            "Building B",
                            "School",
                            "100",
                            "100",
                            "500",
                            "0"});
#line 26
        await testRunner.GivenAsync("the following buildings exist on the site plan:", ((string)(null)), table2, "Given ");
#line hidden
#line 30
        await testRunner.WhenAsync("I run clash detection", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 31
        await testRunner.ThenAsync("no clashes should be detected", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Boundary violation detection")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Clash Detection")]
        [global::Xunit.TraitAttribute("Description", "Boundary violation detection")]
        public async global::System.Threading.Tasks.Task BoundaryViolationDetection()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Boundary violation detection", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 33
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Type",
                            "Width",
                            "Length",
                            "X",
                            "Y"});
                table3.AddRow(new string[] {
                            "Building A",
                            "Office",
                            "200",
                            "200",
                            "900",
                            "400"});
#line 34
        await testRunner.GivenAsync("the following buildings exist on the site plan:", ((string)(null)), table3, "Given ");
#line hidden
#line 37
        await testRunner.WhenAsync("I run clash detection", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 38
        await testRunner.ThenAsync("a clash of type \"BoundaryViolation\" with severity \"Critical\" should be detected f" +
                        "or building \"Building A\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Overlap detection with no separate clearance reported")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Clash Detection")]
        [global::Xunit.TraitAttribute("Description", "Overlap detection with no separate clearance reported")]
        public async global::System.Threading.Tasks.Task OverlapDetectionWithNoSeparateClearanceReported()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Overlap detection with no separate clearance reported", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 40
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Type",
                            "Width",
                            "Length",
                            "X",
                            "Y"});
                table4.AddRow(new string[] {
                            "Building A",
                            "Office",
                            "200",
                            "200",
                            "0",
                            "0"});
                table4.AddRow(new string[] {
                            "Building B",
                            "School",
                            "200",
                            "200",
                            "100",
                            "100"});
#line 41
        await testRunner.GivenAsync("the following buildings exist on the site plan:", ((string)(null)), table4, "Given ");
#line hidden
#line 45
        await testRunner.WhenAsync("I run clash detection", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 46
        await testRunner.ThenAsync("a clash of type \"Overlap\" with severity \"Critical\" should be detected for buildin" +
                        "gs \"Building A\" and \"Building B\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 47
        await testRunner.AndAsync("no clash of type \"InsufficientClearance\" should be detected for buildings \"Buildi" +
                        "ng A\" and \"Building B\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Insufficient clearance for non-overlapping buildings")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Clash Detection")]
        [global::Xunit.TraitAttribute("Description", "Insufficient clearance for non-overlapping buildings")]
        public async global::System.Threading.Tasks.Task InsufficientClearanceForNon_OverlappingBuildings()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Insufficient clearance for non-overlapping buildings", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 49
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Type",
                            "Width",
                            "Length",
                            "X",
                            "Y"});
                table5.AddRow(new string[] {
                            "Building A",
                            "Office",
                            "100",
                            "100",
                            "0",
                            "0"});
                table5.AddRow(new string[] {
                            "Building B",
                            "Office",
                            "100",
                            "100",
                            "105",
                            "0"});
#line 50
        await testRunner.GivenAsync("the following buildings exist on the site plan:", ((string)(null)), table5, "Given ");
#line hidden
#line 54
        await testRunner.WhenAsync("I run clash detection", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 55
        await testRunner.ThenAsync("a clash of type \"InsufficientClearance\" with severity \"Warning\" should be detecte" +
                        "d for buildings \"Building A\" and \"Building B\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Nightclub-school zoning violation")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Clash Detection")]
        [global::Xunit.TraitAttribute("Description", "Nightclub-school zoning violation")]
        public async global::System.Threading.Tasks.Task Nightclub_SchoolZoningViolation()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Nightclub-school zoning violation", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 57
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Type",
                            "Width",
                            "Length",
                            "X",
                            "Y"});
                table6.AddRow(new string[] {
                            "School A",
                            "School",
                            "100",
                            "100",
                            "0",
                            "0"});
                table6.AddRow(new string[] {
                            "Nightclub A",
                            "Nightclub",
                            "100",
                            "100",
                            "150",
                            "0"});
#line 58
        await testRunner.GivenAsync("the following buildings exist on the site plan:", ((string)(null)), table6, "Given ");
#line hidden
#line 62
        await testRunner.WhenAsync("I run clash detection", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 63
        await testRunner.ThenAsync("a clash of type \"ZoningViolation\" with severity \"Warning\" should be detected for " +
                        "buildings \"School A\" and \"Nightclub A\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Residential-stadium zoning violation")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Clash Detection")]
        [global::Xunit.TraitAttribute("Description", "Residential-stadium zoning violation")]
        public async global::System.Threading.Tasks.Task Residential_StadiumZoningViolation()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Residential-stadium zoning violation", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 65
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Type",
                            "Width",
                            "Length",
                            "X",
                            "Y"});
                table7.AddRow(new string[] {
                            "Stadium A",
                            "Stadium",
                            "100",
                            "100",
                            "0",
                            "0"});
                table7.AddRow(new string[] {
                            "Residence A",
                            "ResidentialBuilding",
                            "100",
                            "100",
                            "120",
                            "0"});
#line 66
        await testRunner.GivenAsync("the following buildings exist on the site plan:", ((string)(null)), table7, "Given ");
#line hidden
#line 70
        await testRunner.WhenAsync("I run clash detection", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 71
        await testRunner.ThenAsync("a clash of type \"ZoningViolation\" with severity \"Warning\" should be detected for " +
                        "buildings \"Stadium A\" and \"Residence A\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Residential-nightclub zoning violation")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Clash Detection")]
        [global::Xunit.TraitAttribute("Description", "Residential-nightclub zoning violation")]
        public async global::System.Threading.Tasks.Task Residential_NightclubZoningViolation()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Residential-nightclub zoning violation", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 73
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Type",
                            "Width",
                            "Length",
                            "X",
                            "Y"});
                table8.AddRow(new string[] {
                            "Nightclub A",
                            "Nightclub",
                            "100",
                            "100",
                            "0",
                            "0"});
                table8.AddRow(new string[] {
                            "Residence A",
                            "ResidentialBuilding",
                            "100",
                            "100",
                            "120",
                            "0"});
#line 74
        await testRunner.GivenAsync("the following buildings exist on the site plan:", ((string)(null)), table8, "Given ");
#line hidden
#line 78
        await testRunner.WhenAsync("I run clash detection", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 79
        await testRunner.ThenAsync("a clash of type \"ZoningViolation\" with severity \"Warning\" should be detected for " +
                        "buildings \"Nightclub A\" and \"Residence A\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Multiple violations for same building")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Clash Detection")]
        [global::Xunit.TraitAttribute("Description", "Multiple violations for same building")]
        public async global::System.Threading.Tasks.Task MultipleViolationsForSameBuilding()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Multiple violations for same building", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 81
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Type",
                            "Width",
                            "Length",
                            "X",
                            "Y"});
                table9.AddRow(new string[] {
                            "School A",
                            "School",
                            "100",
                            "100",
                            "0",
                            "0"});
                table9.AddRow(new string[] {
                            "Nightclub A",
                            "Nightclub",
                            "200",
                            "200",
                            "50",
                            "50"});
#line 82
        await testRunner.GivenAsync("the following buildings exist on the site plan:", ((string)(null)), table9, "Given ");
#line hidden
#line 86
        await testRunner.WhenAsync("I run clash detection", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 87
        await testRunner.ThenAsync("a clash of type \"Overlap\" with severity \"Critical\" should be detected for buildin" +
                        "gs \"School A\" and \"Nightclub A\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 88
        await testRunner.AndAsync("a clash of type \"ZoningViolation\" with severity \"Warning\" should be detected for " +
                        "buildings \"School A\" and \"Nightclub A\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 89
        await testRunner.AndAsync("2 clashes should be detected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ClashDetectionFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ClashDetectionFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
