// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace BimCollab.ClashDetection.Specs.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "US1")]
    public partial class ClashDetectionEdgeCasesFeature : object, global::Xunit.IClassFixture<ClashDetectionEdgeCasesFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "US1"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Clash Detection Edge Cases", "    As a BIM system consumer\n    I want edge cases in clash detection to be handl" +
                "ed correctly\n    So that boundary conditions are accurately resolved", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "EdgeCases.feature"
#line hidden
        
        public ClashDetectionEdgeCasesFeature(ClashDetectionEdgeCasesFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/EdgeCases.feature.ndjson", 8);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Empty buildings list returns empty clashes")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Clash Detection Edge Cases")]
        [global::Xunit.TraitAttribute("Description", "Empty buildings list returns empty clashes")]
        public async global::System.Threading.Tasks.Task EmptyBuildingsListReturnsEmptyClashes()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Empty buildings list returns empty clashes", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
        await testRunner.GivenAsync("a site plan with width 1000 and length 500", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Type",
                            "Width",
                            "Length",
                            "X",
                            "Y"});
#line 9
        await testRunner.AndAsync("the following buildings exist on the site plan:", ((string)(null)), table10, "And ");
#line hidden
#line 11
        await testRunner.WhenAsync("I run clash detection", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 12
        await testRunner.ThenAsync("no clashes should be detected", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Single building within bounds produces no clashes")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Clash Detection Edge Cases")]
        [global::Xunit.TraitAttribute("Description", "Single building within bounds produces no clashes")]
        public async global::System.Threading.Tasks.Task SingleBuildingWithinBoundsProducesNoClashes()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Single building within bounds produces no clashes", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 14
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
        await testRunner.GivenAsync("a site plan with width 1000 and length 500", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Type",
                            "Width",
                            "Length",
                            "X",
                            "Y"});
                table11.AddRow(new string[] {
                            "Building A",
                            "Office",
                            "100",
                            "100",
                            "50",
                            "50"});
#line 16
        await testRunner.AndAsync("the following buildings exist on the site plan:", ((string)(null)), table11, "And ");
#line hidden
#line 19
        await testRunner.WhenAsync("I run clash detection", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 20
        await testRunner.ThenAsync("no clashes should be detected", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Single building outside bounds produces boundary violation")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Clash Detection Edge Cases")]
        [global::Xunit.TraitAttribute("Description", "Single building outside bounds produces boundary violation")]
        public async global::System.Threading.Tasks.Task SingleBuildingOutsideBoundsProducesBoundaryViolation()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Single building outside bounds produces boundary violation", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 22
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 23
        await testRunner.GivenAsync("a site plan with width 100 and length 100", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Type",
                            "Width",
                            "Length",
                            "X",
                            "Y"});
                table12.AddRow(new string[] {
                            "Building A",
                            "Office",
                            "50",
                            "50",
                            "80",
                            "80"});
#line 24
        await testRunner.AndAsync("the following buildings exist on the site plan:", ((string)(null)), table12, "And ");
#line hidden
#line 27
        await testRunner.WhenAsync("I run clash detection", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
        await testRunner.ThenAsync("a clash of type \"BoundaryViolation\" with severity \"Critical\" should be detected f" +
                        "or building \"Building A\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Buildings exactly touching are not overlapping but violate clearance")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Clash Detection Edge Cases")]
        [global::Xunit.TraitAttribute("Description", "Buildings exactly touching are not overlapping but violate clearance")]
        public async global::System.Threading.Tasks.Task BuildingsExactlyTouchingAreNotOverlappingButViolateClearance()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Buildings exactly touching are not overlapping but violate clearance", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 30
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 31
        await testRunner.GivenAsync("a site plan with width 1000 and length 500", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Type",
                            "Width",
                            "Length",
                            "X",
                            "Y"});
                table13.AddRow(new string[] {
                            "Building A",
                            "Office",
                            "100",
                            "100",
                            "0",
                            "0"});
                table13.AddRow(new string[] {
                            "Building B",
                            "Office",
                            "100",
                            "100",
                            "100",
                            "0"});
#line 32
        await testRunner.AndAsync("the following buildings exist on the site plan:", ((string)(null)), table13, "And ");
#line hidden
#line 36
        await testRunner.WhenAsync("I run clash detection", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 37
        await testRunner.ThenAsync("no clash of type \"Overlap\" should be detected for buildings \"Building A\" and \"Bui" +
                        "lding B\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 38
        await testRunner.AndAsync("a clash of type \"InsufficientClearance\" with severity \"Warning\" should be detecte" +
                        "d for buildings \"Building A\" and \"Building B\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Buildings exactly 10 units apart have no clearance violation")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Clash Detection Edge Cases")]
        [global::Xunit.TraitAttribute("Description", "Buildings exactly 10 units apart have no clearance violation")]
        public async global::System.Threading.Tasks.Task BuildingsExactly10UnitsApartHaveNoClearanceViolation()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Buildings exactly 10 units apart have no clearance violation", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 40
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 41
        await testRunner.GivenAsync("a site plan with width 1000 and length 500", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Type",
                            "Width",
                            "Length",
                            "X",
                            "Y"});
                table14.AddRow(new string[] {
                            "Building A",
                            "Office",
                            "100",
                            "100",
                            "0",
                            "0"});
                table14.AddRow(new string[] {
                            "Building B",
                            "Office",
                            "100",
                            "100",
                            "110",
                            "0"});
#line 42
        await testRunner.AndAsync("the following buildings exist on the site plan:", ((string)(null)), table14, "And ");
#line hidden
#line 46
        await testRunner.WhenAsync("I run clash detection", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 47
        await testRunner.ThenAsync("no clashes should be detected", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Nightclub exactly 200 units from school has no zoning violation")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Clash Detection Edge Cases")]
        [global::Xunit.TraitAttribute("Description", "Nightclub exactly 200 units from school has no zoning violation")]
        public async global::System.Threading.Tasks.Task NightclubExactly200UnitsFromSchoolHasNoZoningViolation()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Nightclub exactly 200 units from school has no zoning violation", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 49
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 50
        await testRunner.GivenAsync("a site plan with width 1000 and length 500", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Type",
                            "Width",
                            "Length",
                            "X",
                            "Y"});
                table15.AddRow(new string[] {
                            "School A",
                            "School",
                            "100",
                            "100",
                            "0",
                            "0"});
                table15.AddRow(new string[] {
                            "Nightclub A",
                            "Nightclub",
                            "100",
                            "100",
                            "300",
                            "0"});
#line 51
        await testRunner.AndAsync("the following buildings exist on the site plan:", ((string)(null)), table15, "And ");
#line hidden
#line 55
        await testRunner.WhenAsync("I run clash detection", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 56
        await testRunner.ThenAsync("no clashes should be detected", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ClashDetectionEdgeCasesFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ClashDetectionEdgeCasesFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
