// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace BimCollab.ClashDetection.Specs.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "US2")]
    public partial class InputValidationFeature : object, global::Xunit.IClassFixture<InputValidationFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "US2"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Input Validation", "    As a BIM system consumer\n    I want invalid input to be rejected before clash" +
                " detection runs\n    So that I receive clear error messages and no partial result" +
                "s", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "InputValidation.feature"
#line hidden
        
        public InputValidationFeature(InputValidationFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/InputValidation.feature.ndjson", 12);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Missing building name returns validation error")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Input Validation")]
        [global::Xunit.TraitAttribute("Description", "Missing building name returns validation error")]
        public async global::System.Threading.Tasks.Task MissingBuildingNameReturnsValidationError()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Missing building name returns validation error", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
        await testRunner.GivenAsync("a site plan of width 1000 and length 500", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 9
        await testRunner.AndAsync("a building with name \"\" type \"Office\" width 100 length 100 at position 0, 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
        await testRunner.WhenAsync("I submit the clash detection request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 11
        await testRunner.ThenAsync("I should receive a validation error", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 12
        await testRunner.AndAsync("the error should mention \"Name\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Missing building type returns validation error")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Input Validation")]
        [global::Xunit.TraitAttribute("Description", "Missing building type returns validation error")]
        public async global::System.Threading.Tasks.Task MissingBuildingTypeReturnsValidationError()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Missing building type returns validation error", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 14
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
        await testRunner.GivenAsync("a site plan of width 1000 and length 500", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 16
        await testRunner.AndAsync("a building with name \"Building A\" type \"\" width 100 length 100 at position 0, 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
        await testRunner.WhenAsync("I submit the clash detection request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 18
        await testRunner.ThenAsync("I should receive a validation error", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 19
        await testRunner.AndAsync("the error should mention \"Type\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Building width of zero returns validation error")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Input Validation")]
        [global::Xunit.TraitAttribute("Description", "Building width of zero returns validation error")]
        public async global::System.Threading.Tasks.Task BuildingWidthOfZeroReturnsValidationError()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Building width of zero returns validation error", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 21
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 22
        await testRunner.GivenAsync("a site plan of width 1000 and length 500", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 23
        await testRunner.AndAsync("a building with name \"Building A\" type \"Office\" width 0 length 100 at position 0," +
                        " 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
        await testRunner.WhenAsync("I submit the clash detection request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
        await testRunner.ThenAsync("I should receive a validation error", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 26
        await testRunner.AndAsync("the error should mention \"Width\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Negative building length returns validation error")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Input Validation")]
        [global::Xunit.TraitAttribute("Description", "Negative building length returns validation error")]
        public async global::System.Threading.Tasks.Task NegativeBuildingLengthReturnsValidationError()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Negative building length returns validation error", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 28
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 29
        await testRunner.GivenAsync("a site plan of width 1000 and length 500", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 30
        await testRunner.AndAsync("a building with name \"Building A\" type \"Office\" width 100 length -50 at position " +
                        "0, 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
        await testRunner.WhenAsync("I submit the clash detection request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 32
        await testRunner.ThenAsync("I should receive a validation error", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 33
        await testRunner.AndAsync("the error should mention \"Length\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Negative X position returns validation error")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Input Validation")]
        [global::Xunit.TraitAttribute("Description", "Negative X position returns validation error")]
        public async global::System.Threading.Tasks.Task NegativeXPositionReturnsValidationError()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Negative X position returns validation error", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 35
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 36
        await testRunner.GivenAsync("a site plan of width 1000 and length 500", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 37
        await testRunner.AndAsync("a building with name \"Building A\" type \"Office\" width 100 length 100 at position " +
                        "-10, 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
        await testRunner.WhenAsync("I submit the clash detection request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 39
        await testRunner.ThenAsync("I should receive a validation error", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 40
        await testRunner.AndAsync("the error should mention \"X\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Multiple invalid fields reports all errors")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Input Validation")]
        [global::Xunit.TraitAttribute("Description", "Multiple invalid fields reports all errors")]
        public async global::System.Threading.Tasks.Task MultipleInvalidFieldsReportsAllErrors()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Multiple invalid fields reports all errors", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 42
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 43
        await testRunner.GivenAsync("a site plan of width 1000 and length 500", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 44
        await testRunner.AndAsync("a building with name \"\" type \"InvalidType\" width -5 length -10 at position -1, -1" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 45
        await testRunner.WhenAsync("I submit the clash detection request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 46
        await testRunner.ThenAsync("I should receive a validation error", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 47
        await testRunner.AndAsync("the error should mention \"Name\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
        await testRunner.AndAsync("the error should mention \"Type\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
        await testRunner.AndAsync("the error should mention \"Width\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 50
        await testRunner.AndAsync("the error should mention \"Length\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
        await testRunner.AndAsync("the error should mention \"X\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 52
        await testRunner.AndAsync("the error should mention \"Y\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Mix of valid and invalid buildings rejects entire request")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Input Validation")]
        [global::Xunit.TraitAttribute("Description", "Mix of valid and invalid buildings rejects entire request")]
        public async global::System.Threading.Tasks.Task MixOfValidAndInvalidBuildingsRejectsEntireRequest()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Mix of valid and invalid buildings rejects entire request", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 54
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 55
        await testRunner.GivenAsync("a site plan of width 1000 and length 500", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 56
        await testRunner.AndAsync("a building with name \"Valid Building\" type \"Office\" width 100 length 100 at posit" +
                        "ion 0, 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
        await testRunner.AndAsync("a building with name \"\" type \"Office\" width 100 length 100 at position 200, 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 58
        await testRunner.WhenAsync("I submit the clash detection request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 59
        await testRunner.ThenAsync("I should receive a validation error", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 60
        await testRunner.AndAsync("the error should mention \"Name\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Duplicate building names returns validation error")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Input Validation")]
        [global::Xunit.TraitAttribute("Description", "Duplicate building names returns validation error")]
        public async global::System.Threading.Tasks.Task DuplicateBuildingNamesReturnsValidationError()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Duplicate building names returns validation error", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 62
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 63
        await testRunner.GivenAsync("a site plan of width 1000 and length 500", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 64
        await testRunner.AndAsync("a building with name \"Building A\" type \"Office\" width 100 length 100 at position " +
                        "0, 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
        await testRunner.AndAsync("a building with name \"Building A\" type \"School\" width 100 length 100 at position " +
                        "200, 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 66
        await testRunner.WhenAsync("I submit the clash detection request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 67
        await testRunner.ThenAsync("I should receive a validation error", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 68
        await testRunner.AndAsync("the error should mention \"duplicate\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Site plan width of zero returns validation error")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Input Validation")]
        [global::Xunit.TraitAttribute("Description", "Site plan width of zero returns validation error")]
        public async global::System.Threading.Tasks.Task SitePlanWidthOfZeroReturnsValidationError()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Site plan width of zero returns validation error", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 70
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 71
        await testRunner.GivenAsync("a site plan of width 0 and length 500", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 72
        await testRunner.AndAsync("a building with name \"Building A\" type \"Office\" width 100 length 100 at position " +
                        "0, 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 73
        await testRunner.WhenAsync("I submit the clash detection request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 74
        await testRunner.ThenAsync("I should receive a validation error", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 75
        await testRunner.AndAsync("the error should mention \"Width\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Site plan negative length returns validation error")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Input Validation")]
        [global::Xunit.TraitAttribute("Description", "Site plan negative length returns validation error")]
        public async global::System.Threading.Tasks.Task SitePlanNegativeLengthReturnsValidationError()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Site plan negative length returns validation error", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 77
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 78
        await testRunner.GivenAsync("a site plan of width 1000 and length -100", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 79
        await testRunner.AndAsync("a building with name \"Building A\" type \"Office\" width 100 length 100 at position " +
                        "0, 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 80
        await testRunner.WhenAsync("I submit the clash detection request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 81
        await testRunner.ThenAsync("I should receive a validation error", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 82
        await testRunner.AndAsync("the error should mention \"Length\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await InputValidationFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await InputValidationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
